@startuml diagram
actor User
participant EventStore
participant "Handler\n(custom implmentation)" as Handler
participant NotificationStore

EventStore -> Handler : Capture change event
Handler -> NotificationStore : Store notifications to relevant principals
NotificationStore --> User : Notify user (optional)
User -> NotificationStore : Get notifications (filtered by channel)
NotificationStore -> User : Return notifications
User -> NotificationStore : Confirm seen notification (optionally provide channel)


@enduml